drop table if exists HIT;

create table if not exists HIT (
    id              BIGINT generated by default as identity,
    app             VARCHAR(256),
    uri             VARCHAR(512),
    ip              VARCHAR(64),
    timestamp        TIMESTAMP WITHOUT TIME ZONE,
    constraint HIT_PK primary key (id)
);

CREATE UNIQUE INDEX HIT_idx ON HIT (id);
