
CREATE TABLE IF NOT EXISTS users (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) NOT NULL UNIQUE,
    email   VARCHAR(255) NOT NULL UNIQUE
);


CREATE TABLE if  NOT EXISTS locations (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE if  NOT EXISTS events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category           BIGINT REFERENCES categories (id) ON DELETE RESTRICT,
    initiator          BIGINT REFERENCES users (id) ON DELETE CASCADE,
    annotation         VARCHAR(2000),
    description        VARCHAR(7000),
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    event_date         TIMESTAMP WITHOUT TIME ZONE,
    location           BIGINT REFERENCES locations (id) ON DELETE CASCADE,
    paid               BOOLEAN,
    participant_limit  INTEGER,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN,
    state              VARCHAR(16),
    title              VARCHAR(120)
);

CREATE TABLE if  NOT EXISTS compilations (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN,
    title  VARCHAR(128) NOT NULL
);

CREATE TABLE if  NOT EXISTS events_to_compilations (
    event_id       BIGINT REFERENCES events (id) ON DELETE CASCADE,
    compilation_id BIGINT REFERENCES compilations (id) ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS requests (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester BIGINT REFERENCES users (id) ON DELETE CASCADE,
    event     BIGINT REFERENCES events (id) ON DELETE CASCADE,
    created   TIMESTAMP WITHOUT TIME ZONE,
    status    VARCHAR(16) NOT NULL
);